export const DISTRICTS = ["THIRUVANANTHAPURAM","KOLLAM","PATHANAMTHITTA","ALAPPUZHA","KOTTAYAM","IDUKKI","ERNAKULAM","THRISSUR","PALAKKAD","MALAPPURAM","KOZHIKODE","WAYANAD","KANNUR","KASARAGOD"] as const;
export const TIMEZONE = "Asia/Kolkata";
export const DUPLICATE_MESSAGE = "A REGISTRATION WITH THE SAME NAME, DATE OF BIRTH AND WHATSAPP NUMBER ALREADY EXISTS. PLEASE USE YOUR EXISTING REGISTRATION ID OR CONTACT THE ORGANISING TEAM.";
