create extension if not exists pgcrypto;

create type public.staff_role as enum ('admin','coordinator');
create type public.gender as enum ('male','female');
create type public.participant_category as enum ('junior','senior','super_senior');
create type public.eligibility_gender as enum ('male','female','general');
create type public.eligibility_category as enum ('junior','senior','super_senior','general');
create type public.program_status as enum ('not_started','ongoing','closed');
create type public.progress_status as enum ('not_started','ongoing','claimed_submitted');
create type public.verification_status as enum ('not_submitted','pending_verification','verified','rejected','resubmission_required');

create table public.profiles (id uuid primary key default gen_random_uuid(), auth_user_id uuid unique not null references auth.users(id) on delete cascade, username text unique not null, name text not null, whatsapp_number text not null check(whatsapp_number~'^[6-9][0-9]{9}$'), role staff_role not null, must_change_password boolean not null default true, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.groups (id uuid primary key default gen_random_uuid(), name text unique not null, whatsapp_group_link text, primary_coordinator_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), is_active boolean not null default true);
create table public.participants (id uuid primary key default gen_random_uuid(), registration_id text unique not null check(registration_id~'^RF[MF][JSP][A-HJ-NP-Z2-9]{8}$'), access_code_hash text not null, name text not null, place text not null, district text not null check(district=any(array['THIRUVANANTHAPURAM','KOLLAM','PATHANAMTHITTA','ALAPPUZHA','KOTTAYAM','IDUKKI','ERNAKULAM','THRISSUR','PALAKKAD','MALAPPURAM','KOZHIKODE','WAYANAD','KANNUR','KASARAGOD'])), date_of_birth date not null, age_at_registration integer not null check(age_at_registration>=15), gender gender not null, category participant_category not null, whatsapp_number text not null check(whatsapp_number~'^[6-9][0-9]{9}$'), phone_number text not null check(phone_number~'^[6-9][0-9]{9}$'), group_id uuid references public.groups(id) on delete set null, coordinator_id uuid references public.profiles(id) on delete set null, registered_at timestamptz not null default now(), updated_at timestamptz not null default now(), is_active boolean not null default true, deleted_at timestamptz, constraint participant_soft_delete check((is_active and deleted_at is null) or (not is_active)));
create unique index participants_duplicate_guard on public.participants(name,date_of_birth,whatsapp_number) where deleted_at is null;
create index participants_name_idx on public.participants(name); create index participants_whatsapp_idx on public.participants(whatsapp_number); create index participants_category_idx on public.participants(category); create index participants_gender_idx on public.participants(gender); create index participants_district_idx on public.participants(district); create index participants_group_idx on public.participants(group_id);
create table public.programs (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, description text, gender_eligibility eligibility_gender not null, category_eligibility eligibility_category not null, submission_form_url text, registration_id_entry_key text, full_name_entry_key text, global_status program_status not null default 'not_started', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.participant_programs (id uuid primary key default gen_random_uuid(), participant_id uuid not null references public.participants(id) on delete cascade, program_id uuid not null references public.programs(id) on delete cascade, participant_progress_status progress_status not null default 'not_started', verification_status verification_status not null default 'not_submitted', selected_at timestamptz not null default now(), form_opened_at timestamptz, claimed_submitted_at timestamptz, verified_at timestamptz, verified_by uuid references public.profiles(id) on delete set null, rejected_at timestamptz, rejection_reason text, admin_note text, coordinator_note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(participant_id,program_id));
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_user_id uuid references auth.users(id) on delete set null, actor_role text, action text not null, entity_type text not null, entity_id text, old_data jsonb, new_data jsonb, created_at timestamptz not null default now(), ip_address inet, user_agent text);
create table public.app_settings (id boolean primary key default true check(id), festival_name text not null default 'AHLU SAADA MEELAD FEST', registration_open_at timestamptz, registration_close_at timestamptz, program_selection_open_at timestamptz, program_selection_close_at timestamptz, maximum_programs_per_participant integer not null default 4 check(maximum_programs_per_participant between 1 and 20), timezone text not null default 'Asia/Kolkata' check(timezone='Asia/Kolkata'), minimum_age integer not null default 15 check(minimum_age>=15), registration_enabled boolean not null default true, contact_number text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
insert into public.app_settings(id) values(true);
create table public.login_attempts (id bigint generated always as identity primary key, login_type text not null check(login_type in('participant','staff')), login_identifier_hash text not null, ip_address inet, succeeded boolean not null, attempted_at timestamptz not null default now()); create index login_attempt_lookup on public.login_attempts(login_identifier_hash,attempted_at desc);
create table public.access_code_resets (id uuid primary key default gen_random_uuid(), participant_id uuid not null references public.participants(id), reset_by uuid not null references public.profiles(id), reset_at timestamptz not null default now(), reason text not null check(length(trim(reason))>=5));
create table public.export_logs (id uuid primary key default gen_random_uuid(), exported_by uuid not null references public.profiles(id), role staff_role not null, export_type text not null, filters jsonb not null default '{}', record_count integer not null check(record_count>=0), created_at timestamptz not null default now());

create function public.touch_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end$$;
do $$declare t text;begin foreach t in array array['profiles','groups','participants','programs','participant_programs','app_settings'] loop execute format('create trigger touch_updated_at before update on public.%I for each row execute function public.touch_updated_at()',t);end loop;end$$;
create function public.current_profile() returns public.profiles stable language sql security definer set search_path='' as $$select * from public.profiles where auth_user_id=auth.uid() and is_active limit 1$$;
create function public.is_admin() returns boolean stable language sql security definer set search_path='' as $$select coalesce((select role='admin' from public.profiles where auth_user_id=auth.uid() and is_active),false)$$;
create function public.is_assigned_coordinator(participant public.participants) returns boolean stable language sql security definer set search_path='' as $$select exists(select 1 from public.profiles p where p.auth_user_id=auth.uid() and p.is_active and p.role='coordinator' and (participant.coordinator_id=p.id or exists(select 1 from public.groups g where g.id=participant.group_id and g.primary_coordinator_id=p.id)))$$;

alter table public.profiles enable row level security; alter table public.groups enable row level security; alter table public.participants enable row level security; alter table public.programs enable row level security; alter table public.participant_programs enable row level security; alter table public.audit_logs enable row level security; alter table public.app_settings enable row level security; alter table public.login_attempts enable row level security; alter table public.access_code_resets enable row level security; alter table public.export_logs enable row level security;
create policy profiles_self_or_admin on public.profiles for select using(auth_user_id=auth.uid() or public.is_admin());
create policy groups_staff_read on public.groups for select to authenticated using(public.is_admin() or primary_coordinator_id=(public.current_profile()).id);
create policy participants_staff_read on public.participants for select to authenticated using(public.is_admin() or public.is_assigned_coordinator(participants));
create policy participants_staff_update on public.participants for update to authenticated using(public.is_admin() or public.is_assigned_coordinator(participants)) with check(public.is_admin() or public.is_assigned_coordinator(participants));
create policy programs_staff_read on public.programs for select to authenticated using(true);
create policy programs_admin_write on public.programs for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy selections_staff_read on public.participant_programs for select to authenticated using(exists(select 1 from public.participants p where p.id=participant_id and (public.is_admin() or public.is_assigned_coordinator(p))));
create policy selections_staff_update on public.participant_programs for update to authenticated using(exists(select 1 from public.participants p where p.id=participant_id and (public.is_admin() or public.is_assigned_coordinator(p))));
create policy audit_admin_read on public.audit_logs for select to authenticated using(public.is_admin());
create policy settings_staff_read on public.app_settings for select to authenticated using(true); create policy settings_admin_write on public.app_settings for update to authenticated using(public.is_admin());
revoke all on all tables in schema public from anon; revoke all on all functions in schema public from anon;
